
version: 2

sources:
  - name: raw
    schema: raw_gz_data
    tables:
      - name: sales
        identifier: raw_gz_sales
        description: "All sales information stored in this table"
        tests:
          - unique:
              column_name: "concat(orders_id, '-', pdt_id)"
        columns:
          - name: date_date
            description: "date of the sale"
            tests:
              - not_null
          - name: orders_id
            description: "unique order id of the sale"
            tests:
              - not_null
      - name: product
        identifier: raw_gz_product
        description: "Information about products in gwz"
        columns:
          - name: products_id
            description: "id of the product"
            tests:
              - not_null
              - unique
                                   

models:
  - name: order_details
    description: "order details including total qty and revenue"
    